// Todo ícone lucide-react usado em algum lugar do site (nomes reais do
// pacote, ex: "TrendingDown"). Fonte única pro gerador do sprite
// (scripts/generate-icon-sprite.mjs); a contraparte client-side é
// src/components/Icon.tsx, que precisa exportar exatamente o mesmo
// conjunto (mesmo padrão de scripts/lib/images.mjs vs. src/lib/images.ts) —
// ao adicionar um ícone novo em qualquer componente, adicione aqui e lá
// também, depois rode "npm run generate-icon-sprite".
export const ICON_NAMES = [
  'ArrowLeftRight',
  'Baby',
  'BadgeCheck',
  'Bell',
  'BookOpen',
  'Cake',
  'CalendarDays',
  'Check',
  'CheckCircle2',
  'ChevronDown',
  'ChevronLeft',
  'ChevronRight',
  'Clock',
  'Copy',
  'Crown',
  'Flame',
  'Gift',
  'Heart',
  'HelpCircle',
  'Home',
  'Info',
  'Link2',
  'Lock',
  'Mail',
  'Menu',
  'MessageCircle',
  'PartyPopper',
  'PawPrint',
  'Percent',
  'Play',
  'Plus',
  'RefreshCw',
  'Search',
  'Send',
  'Share2',
  'ShieldCheck',
  'Shirt',
  'ShoppingBag',
  'Sparkles',
  'Star',
  'Store',
  'Tag',
  'Ticket',
  'Trash2',
  'TrendingDown',
  'TrendingUp',
  'X',
]
